title = "dpi0's space"
base_url = "/"
description = "a space for dpi0"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
highlight_theme = "solarized-dark"
render_emoji = true
smart_punctuation = true

[extra]
date_format = "%d %b, %Y"
webserver_sends_csp_headers = true

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = false

[[extra.main_menu]]
name = "home"
url = "@/_index.md"

# [[extra.main_menu]]
# name = "bear"
# url = "@/bear.md"

# [[extra.main_menu]]
# name = "zola"
# url = "@/zola.md"

[[extra.main_menu]]
name = "writings"
url = "@/writings/_index.md"

# [[extra.main_menu]]
# name = "thoughts"
# url = "@/thoughts/_index.md"
