on: push
name: Build and Deploy GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    # ON PUSH TO "minimal-bear" BRANCH
    if: github.ref == 'refs/heads/minimal-bear'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          # TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
